[textfiles]
pattern = ".*\\.(rtf|rtfd|md|txt|docx?|rtf|html?|pdf|log)$"

[data]
pattern = ".*\\.(ab1|csv|sam|fasta|fastq|fa|fna|faa|gbk?|gbf|gff|numbers|aln|zip|tar.gz|xlsx?|sqlite|json?)$"

[scripts]
pattern = ".*\\.(rmd|go|sql|pl|py|sh|rb|js|ts|coffee|c|r|R|ipynb)$"

[images]
pattern = ".*\\.(svg|jpe?g|png|gif|gifv|bmp|mp4|mov|m4v|ai|webp)$"
