# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            architecture: arm64
            runner: macos-14 # m1
          - os: macos-latest
            architecture: x64
            runner: macos-13 # x86
          - os: ubuntu-latest
            architecture: x64
            runner: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Display the release tag
        run: |
          echo ${{ github.event.release.tag_name }}

      - name: Rename binary
        run: |
          mv deskclean deskclean-${{ github.event.release.tag_name}}-${{ matrix.os }}-${{ matrix.architecture }}

      - name: Upload Deskclean binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: deskclean-*
          file_glob: true
